import type { DriverDTO } from "./_types"

export const mockDrivers: DriverDTO[] = [
    {
        id: "1",
        name: "Daniel Cooper",
        phone: "+1 408-555-7320",
        avatar: "https://randomuser.me/api/portraits/men/32.jpg",
        status: "on-route",
        currentJob: "Express Delivery",
        route: { origin: "San Francisco", destination: "Los Angeles" },
    },
    {
        id: "2",
        name: "Ava Martinez",
        phone: "+1 206-555-0011",
        avatar: "https://randomuser.me/api/portraits/women/44.jpg",
        status: "on-route",
        currentJob: "Furniture Move",
        route: { origin: "Seattle", destination: "Portland" },
    },
    {
        id: "3",
        name: "Oscar Liam",
        phone: "+1 646-555-7780",
        avatar: "https://randomuser.me/api/portraits/men/75.jpg",
        status: "available",
    },
    {
        id: "4",
        name: "Dina Choi",
        phone: "+1 718-555-4410",
        avatar: "https://randomuser.me/api/portraits/women/68.jpg",
        status: "available",
    },
    {
        id: "5",
        name: "Jake Huang",
        phone: "+1 867-555-2130",
        avatar: "https://randomuser.me/api/portraits/men/22.jpg",
        status: "off-duty",
    },
    {
        id: "6",
        name: "Leo Fernandez",
        phone: "+1 213-555-0813",
        avatar: "https://randomuser.me/api/portraits/men/45.jpg",
        status: "on-route",
        currentJob: "Appliance Delivery",
        route: { origin: "Austin", destination: "Houston" },
    },
    {
        id: "7",
        name: "Hana Lee",
        phone: "+1 415-555-8751",
        avatar: "https://randomuser.me/api/portraits/women/33.jpg",
        status: "on-route",
        currentJob: "Package Pickup",
        route: { origin: "Denver", destination: "Salt Lake City" },
    },
    {
        id: "8",
        name: "Chris Jordan",
        phone: "+1 929-555-5546",
        avatar: "https://randomuser.me/api/portraits/men/52.jpg",
        status: "available",
    },
    {
        id: "9",
        name: "Linda Torres",
        phone: "+1 702-555-8800",
        avatar: "https://randomuser.me/api/portraits/women/26.jpg",
        status: "off-duty",
    },
    {
        id: "10",
        name: "Marcus Williams",
        phone: "+1 305-555-1234",
        avatar: "https://randomuser.me/api/portraits/men/36.jpg",
        status: "available",
    },
    {
        id: "11",
        name: "Sofia Rahman",
        phone: "+1 512-555-9876",
        avatar: "https://randomuser.me/api/portraits/women/55.jpg",
        status: "on-route",
        currentJob: "Warehouse Transfer",
        route: { origin: "Phoenix", destination: "Tucson" },
    },
    {
        id: "12",
        name: "Ryan O'Brien",
        phone: "+1 617-555-4321",
        avatar: "https://randomuser.me/api/portraits/men/18.jpg",
        status: "off-duty",
    },
]
